
  deploy:
    needs: push-images
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/01-namespace.yaml
          kubectl apply -f k8s/02-secrets.yaml
          kubectl apply -f k8s/03-configmap.yaml
          kubectl apply -f k8s/04-mongodb-pvc.yaml
          kubectl apply -f k8s/05-mongodb-deployment.yaml
          kubectl apply -f k8s/06-mongodb-service.yaml
          kubectl apply -f k8s/07-backend-deployment.yaml
          kubectl apply -f k8s/08-backend-service.yaml
          kubectl apply -f k8s/09-frontend-deployment.yaml
          kubectl apply -f k8s/10-frontend-service.yaml
      
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/backend -n recruitment-app
          kubectl rollout status deployment/frontend -n recruitment-app
          kubectl get pods -n recruitment-app
